"""Exact-integer 2D affine lattice arithmetic.

Everything here uses Python integers exclusively: no floating point is
involved anywhere in the lattice mathematics, so every returned coordinate,
determinant and congruence is exactly reproducible.

Canonical representation
------------------------
A rank-2 integer affine lattice is a coset ``L = o + H Z^2`` where the basis
matrix is the *column* lower-triangular Hermite normal form

        H = [[ h, 0 ],
             [ r, q ]]

with ``h > 0``, ``q > 0`` and ``0 <= r < q``.  ``det(H) = h*q`` equals the
(positive) unit-cell area / index of the lattice in ``Z^2``.  The canonical
coset origin ``o = (ox, oy)`` is the unique lattice point in the half-open
box ``0 <= ox < h`` and ``0 <= oy < q``.
"""

from __future__ import annotations

from typing import Optional, Tuple

Vec2 = Tuple[int, int]
Mat2 = Tuple[Tuple[int, int], Tuple[int, int]]  # row-major, columns are vectors


def extgcd(a: int, b: int) -> Tuple[int, int, int]:
    """Return ``(g, s, t)`` with ``g > 0`` and ``s*a + t*b == g == gcd(a,b)``."""
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r != 0:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    if old_r < 0:
        old_r, old_s, old_t = -old_r, -old_s, -old_t
    return old_r, old_s, old_t


def hnf22(basis: Tuple[Vec2, Vec2]) -> Mat2:
    """Column-style Hermite normal form of a full-rank 2x2 integer matrix.

    ``basis`` is the pair of column vectors ``(u, v)``.  Returns the canonical
    lower-triangular matrix ``((h, 0), (r, q))`` with ``h,q > 0`` and
    ``0 <= r < q``.  The lattice generated by the columns is unchanged.
    """
    (a, c), (b, d) = basis  # matrix [[a, b], [c, d]], columns u=(a,c), v=(b,d)
    det = a * d - b * c
    if det == 0:
        raise ValueError("hnf22 requires a full-rank (non-collinear) basis")

    # First column of the unimodular transform makes the top entry h = gcd(a,b)
    g, s, t = extgcd(a, b)
    h21 = c * s + d * t          # bottom entry paired with h = g
    q = det // g                 # bottom-right, |q| = det / g (may be negative)

    # Normalize q positive by negating the second column only; the first
    # column (g, h21) is untouched by that operation.
    if q < 0:
        q = -q

    # Column HNF reduction: col1 <- col1 + k*col2 so that 0 <= h21 < q.
    r = h21 % q
    return ((g, 0), (r, q))


def canonical_origin(H: Mat2, member: Vec2) -> Vec2:
    """Canonical coset origin ``o`` for a lattice containing ``member``.

    Returns the unique lattice point ``o`` with ``0 <= ox < h`` and
    ``0 <= oy < q``.
    """
    (h, _), (r, q) = H
    px, py = member
    k1 = px // h                 # makes ox = px - h*k1 lie in [0, h)
    ox = px - h * k1
    k2 = (py - r * k1) // q      # makes oy lie in [0, q)
    oy = py - r * k1 - q * k2
    return (ox, oy)


def lattice_key(H: Mat2, origin: Vec2) -> Tuple[int, int, int, int, int]:
    """Total-order key uniquely identifying a canonical affine lattice."""
    (h, _), (r, q) = H
    ox, oy = origin
    return (h, r, q, ox, oy)


def member_coord(H: Mat2, origin: Vec2, p: Vec2) -> Optional[Tuple[int, int]]:
    """Integer lattice coordinates ``(m, n)`` with ``p == o + H*(m,n)``.

    Returns ``None`` when ``p`` is not a lattice point.  All checks are exact
    divisibility tests; negative coordinates are handled by Python's floor
    division.
    """
    (h, _), (r, q) = H
    ox, oy = origin
    dx = p[0] - ox
    dy = p[1] - oy
    if dx % h != 0:
        return None
    m = dx // h
    num = dy - r * m
    if num % q != 0:
        return None
    n = num // q
    return (m, n)


def area(H: Mat2) -> int:
    """Absolute determinant of the basis matrix (unit-cell area)."""
    (h, _), (_, q) = H
    return h * q
